// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoTriggersSearchResultDeleteResponse
    /// </summary>
    public partial class DtoTriggersSearchResultDeleteResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoTriggersSearchResultDeleteResponse" /> class.
        /// </summary>
        /// <param name="pagerId">pagerId</param>
        [JsonConstructor]
        public DtoTriggersSearchResultDeleteResponse(Option<string> pagerId = default)
        {
            PagerIdOption = pagerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PagerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PagerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PagerId
        /// </summary>
        /* <example>292516ed-4924-4154-a62c-ebe312431fce</example> */
        [JsonPropertyName("pager_id")]
        public string PagerId { get { return this.PagerIdOption; } set { this.PagerIdOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoTriggersSearchResultDeleteResponse {\n");
            sb.Append("  PagerId: ").Append(PagerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoTriggersSearchResultDeleteResponse" />
    /// </summary>
    public class DtoTriggersSearchResultDeleteResponseJsonConverter : JsonConverter<DtoTriggersSearchResultDeleteResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoTriggersSearchResultDeleteResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoTriggersSearchResultDeleteResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> pagerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pager_id":
                            pagerId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (pagerId.IsSet && pagerId.Value == null)
                throw new ArgumentNullException(nameof(pagerId), "Property is not nullable for class DtoTriggersSearchResultDeleteResponse.");

            return new DtoTriggersSearchResultDeleteResponse(pagerId);
        }

        /// <summary>
        /// Serializes a <see cref="DtoTriggersSearchResultDeleteResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoTriggersSearchResultDeleteResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoTriggersSearchResultDeleteResponse dtoTriggersSearchResultDeleteResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoTriggersSearchResultDeleteResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoTriggersSearchResultDeleteResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoTriggersSearchResultDeleteResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoTriggersSearchResultDeleteResponse dtoTriggersSearchResultDeleteResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoTriggersSearchResultDeleteResponse.PagerIdOption.IsSet && dtoTriggersSearchResultDeleteResponse.PagerId == null)
                throw new ArgumentNullException(nameof(dtoTriggersSearchResultDeleteResponse.PagerId), "Property is required for class DtoTriggersSearchResultDeleteResponse.");

            if (dtoTriggersSearchResultDeleteResponse.PagerIdOption.IsSet)
                writer.WriteString("pager_id", dtoTriggersSearchResultDeleteResponse.PagerId);
        }
    }
}
