// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoUserSettings
    /// </summary>
    public partial class DtoUserSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoUserSettings" /> class.
        /// </summary>
        /// <param name="authEnabled">authEnabled</param>
        /// <param name="contacts">contacts</param>
        /// <param name="login">login</param>
        /// <param name="role">role</param>
        /// <param name="subscriptions">subscriptions</param>
        [JsonConstructor]
        public DtoUserSettings(Option<bool?> authEnabled = default, Option<List<DtoContactWithScore>> contacts = default, Option<string> login = default, Option<string> role = default, Option<List<DtoSubscription>> subscriptions = default)
        {
            AuthEnabledOption = authEnabled;
            ContactsOption = contacts;
            LoginOption = login;
            RoleOption = role;
            SubscriptionsOption = subscriptions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AuthEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AuthEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets AuthEnabled
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("auth_enabled")]
        public bool? AuthEnabled { get { return this.AuthEnabledOption; } set { this.AuthEnabledOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Contacts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DtoContactWithScore>> ContactsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Contacts
        /// </summary>
        [JsonPropertyName("contacts")]
        public List<DtoContactWithScore> Contacts { get { return this.ContactsOption; } set { this.ContactsOption = new Option<List<DtoContactWithScore>>(value); } }

        /// <summary>
        /// Used to track the state of Login
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> LoginOption { get; private set; }

        /// <summary>
        /// Gets or Sets Login
        /// </summary>
        /* <example>john</example> */
        [JsonPropertyName("login")]
        public string Login { get { return this.LoginOption; } set { this.LoginOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        /* <example>user</example> */
        [JsonPropertyName("role")]
        public string Role { get { return this.RoleOption; } set { this.RoleOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Subscriptions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DtoSubscription>> SubscriptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subscriptions
        /// </summary>
        [JsonPropertyName("subscriptions")]
        public List<DtoSubscription> Subscriptions { get { return this.SubscriptionsOption; } set { this.SubscriptionsOption = new Option<List<DtoSubscription>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoUserSettings {\n");
            sb.Append("  AuthEnabled: ").Append(AuthEnabled).Append("\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  Login: ").Append(Login).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Subscriptions: ").Append(Subscriptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoUserSettings" />
    /// </summary>
    public class DtoUserSettingsJsonConverter : JsonConverter<DtoUserSettings>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoUserSettings" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoUserSettings Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> authEnabled = default;
            Option<List<DtoContactWithScore>> contacts = default;
            Option<string> login = default;
            Option<string> role = default;
            Option<List<DtoSubscription>> subscriptions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "auth_enabled":
                            authEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "contacts":
                            contacts = new Option<List<DtoContactWithScore>>(JsonSerializer.Deserialize<List<DtoContactWithScore>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "login":
                            login = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "role":
                            role = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "subscriptions":
                            subscriptions = new Option<List<DtoSubscription>>(JsonSerializer.Deserialize<List<DtoSubscription>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (authEnabled.IsSet && authEnabled.Value == null)
                throw new ArgumentNullException(nameof(authEnabled), "Property is not nullable for class DtoUserSettings.");

            if (contacts.IsSet && contacts.Value == null)
                throw new ArgumentNullException(nameof(contacts), "Property is not nullable for class DtoUserSettings.");

            if (login.IsSet && login.Value == null)
                throw new ArgumentNullException(nameof(login), "Property is not nullable for class DtoUserSettings.");

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class DtoUserSettings.");

            if (subscriptions.IsSet && subscriptions.Value == null)
                throw new ArgumentNullException(nameof(subscriptions), "Property is not nullable for class DtoUserSettings.");

            return new DtoUserSettings(authEnabled, contacts, login, role, subscriptions);
        }

        /// <summary>
        /// Serializes a <see cref="DtoUserSettings" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoUserSettings"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoUserSettings dtoUserSettings, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoUserSettings, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoUserSettings" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoUserSettings"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoUserSettings dtoUserSettings, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoUserSettings.ContactsOption.IsSet && dtoUserSettings.Contacts == null)
                throw new ArgumentNullException(nameof(dtoUserSettings.Contacts), "Property is required for class DtoUserSettings.");

            if (dtoUserSettings.LoginOption.IsSet && dtoUserSettings.Login == null)
                throw new ArgumentNullException(nameof(dtoUserSettings.Login), "Property is required for class DtoUserSettings.");

            if (dtoUserSettings.RoleOption.IsSet && dtoUserSettings.Role == null)
                throw new ArgumentNullException(nameof(dtoUserSettings.Role), "Property is required for class DtoUserSettings.");

            if (dtoUserSettings.SubscriptionsOption.IsSet && dtoUserSettings.Subscriptions == null)
                throw new ArgumentNullException(nameof(dtoUserSettings.Subscriptions), "Property is required for class DtoUserSettings.");

            if (dtoUserSettings.AuthEnabledOption.IsSet)
                writer.WriteBoolean("auth_enabled", dtoUserSettings.AuthEnabledOption.Value.Value);

            if (dtoUserSettings.ContactsOption.IsSet)
            {
                writer.WritePropertyName("contacts");
                JsonSerializer.Serialize(writer, dtoUserSettings.Contacts, jsonSerializerOptions);
            }
            if (dtoUserSettings.LoginOption.IsSet)
                writer.WriteString("login", dtoUserSettings.Login);

            if (dtoUserSettings.RoleOption.IsSet)
                writer.WriteString("role", dtoUserSettings.Role);

            if (dtoUserSettings.SubscriptionsOption.IsSet)
            {
                writer.WritePropertyName("subscriptions");
                JsonSerializer.Serialize(writer, dtoUserSettings.Subscriptions, jsonSerializerOptions);
            }
        }
    }
}
