// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// MoiraMaintenanceInfo
    /// </summary>
    public partial class MoiraMaintenanceInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoiraMaintenanceInfo" /> class.
        /// </summary>
        /// <param name="removeTime">removeTime</param>
        /// <param name="removeUser">removeUser</param>
        /// <param name="setupTime">setupTime</param>
        /// <param name="setupUser">setupUser</param>
        [JsonConstructor]
        public MoiraMaintenanceInfo(Option<long?> removeTime = default, Option<string> removeUser = default, Option<long?> setupTime = default, Option<string> setupUser = default)
        {
            RemoveTimeOption = removeTime;
            RemoveUserOption = removeUser;
            SetupTimeOption = setupTime;
            SetupUserOption = setupUser;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of RemoveTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> RemoveTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets RemoveTime
        /// </summary>
        /* <example>0</example> */
        [JsonPropertyName("remove_time")]
        public long? RemoveTime { get { return this.RemoveTimeOption; } set { this.RemoveTimeOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of RemoveUser
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RemoveUserOption { get; private set; }

        /// <summary>
        /// Gets or Sets RemoveUser
        /// </summary>
        [JsonPropertyName("remove_user")]
        public string RemoveUser { get { return this.RemoveUserOption; } set { this.RemoveUserOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of SetupTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SetupTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets SetupTime
        /// </summary>
        /* <example>0</example> */
        [JsonPropertyName("setup_time")]
        public long? SetupTime { get { return this.SetupTimeOption; } set { this.SetupTimeOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of SetupUser
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> SetupUserOption { get; private set; }

        /// <summary>
        /// Gets or Sets SetupUser
        /// </summary>
        [JsonPropertyName("setup_user")]
        public string SetupUser { get { return this.SetupUserOption; } set { this.SetupUserOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MoiraMaintenanceInfo {\n");
            sb.Append("  RemoveTime: ").Append(RemoveTime).Append("\n");
            sb.Append("  RemoveUser: ").Append(RemoveUser).Append("\n");
            sb.Append("  SetupTime: ").Append(SetupTime).Append("\n");
            sb.Append("  SetupUser: ").Append(SetupUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MoiraMaintenanceInfo" />
    /// </summary>
    public class MoiraMaintenanceInfoJsonConverter : JsonConverter<MoiraMaintenanceInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="MoiraMaintenanceInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MoiraMaintenanceInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> removeTime = default;
            Option<string> removeUser = default;
            Option<long?> setupTime = default;
            Option<string> setupUser = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "remove_time":
                            removeTime = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "remove_user":
                            removeUser = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "setup_time":
                            setupTime = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "setup_user":
                            setupUser = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new MoiraMaintenanceInfo(removeTime, removeUser, setupTime, setupUser);
        }

        /// <summary>
        /// Serializes a <see cref="MoiraMaintenanceInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="moiraMaintenanceInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MoiraMaintenanceInfo moiraMaintenanceInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, moiraMaintenanceInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MoiraMaintenanceInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="moiraMaintenanceInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MoiraMaintenanceInfo moiraMaintenanceInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (moiraMaintenanceInfo.RemoveTimeOption.IsSet)
                if (moiraMaintenanceInfo.RemoveTimeOption.Value != null)
                    writer.WriteNumber("remove_time", moiraMaintenanceInfo.RemoveTimeOption.Value.Value);
                else
                    writer.WriteNull("remove_time");

            if (moiraMaintenanceInfo.RemoveUserOption.IsSet)
                if (moiraMaintenanceInfo.RemoveUserOption.Value != null)
                    writer.WriteString("remove_user", moiraMaintenanceInfo.RemoveUser);
                else
                    writer.WriteNull("remove_user");

            if (moiraMaintenanceInfo.SetupTimeOption.IsSet)
                if (moiraMaintenanceInfo.SetupTimeOption.Value != null)
                    writer.WriteNumber("setup_time", moiraMaintenanceInfo.SetupTimeOption.Value.Value);
                else
                    writer.WriteNull("setup_time");

            if (moiraMaintenanceInfo.SetupUserOption.IsSet)
                if (moiraMaintenanceInfo.SetupUserOption.Value != null)
                    writer.WriteString("setup_user", moiraMaintenanceInfo.SetupUser);
                else
                    writer.WriteNull("setup_user");
        }
    }
}
